version: "3.4"

services:
  cinemasystem:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:443;http://+:80
    depends_on:
      - postgres
    ports:
      - 5000:80
      - 443
  postgres:
    image: postgres
    restart: always
    ports:
      - 6000:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cinemadb
  #   volumes:
  #      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
